[secret_keys]
henkan = "abcdefghijklmnopqrstuvwxyz"
# このアルファベットを使ってmqttに流すデータを暗号化しています。
# アルファベットが重複しないように並べ替えたものを使ってください。
# 同じものをpicoWにも設定してください。

topic = "tkj/remote/2025/sw012345" 
# mqttトピックス topic
# topicは必ず変更してください。picW側と合わせてください。